server:
  port: 8887

spring:
  application:
    name: youxu-shop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///group_shop?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: admin

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true

dubbo:
  protocol:
    # dubbo 协议
     name: dubbo
     port: 20891
  scan:
    base-packages: cn.youxu
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  application:
    name: youxu-shop
  registry:
    address: zookeeper://127.0.0.1:2181
    simplified: true

tengxun:
  cos_secretid: AKID3uWnAHGl7G9rMbCNsSpxsZ1D9pIYtIm0
  cos_secretkey: 81gCxYzA6nEPN7bpnWrwlNnx50g6GAsM
  cos_region: ap-nanjing
  bucket_name: group-shop-1301453407

logging:
  level:
    cn.youxu.shop.mapper: DEBUG